name: Amqp Create Release

# When a tag is pushed, create a release
on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
env:
  TZ: Asia/Shanghai

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all tags

      - name: Create Release for Tag
        id: release_tag
        uses: Akryum/release-tag
        env:
          GITHUB_TOKEN: ${{ secrets.AMQP_TOKEN }}
        with:
          tag_name: ${{ github.ref }}